### ISSUE TITLE
`RackNetworkConfig`: Use stronger types than `String`?

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/omicron#3397]
When @jmpesp was testing #3387 in the Canada region, we tried running with a `RackNetworkConfig` of:

```toml
[rack_network_config]
gateway_ip = ""
infra_ip_first = ""
infra_ip_last = ""
uplink_port = ""
uplink_port_speed = "speed_10g"
uplink_port_fec = "none"
uplink_ip = ""
```

This is "valid" as far as type type system is concerned: the two enum values (`uplink_port_{speed,fec}`) have valid values, and the remaining values are all `String`s; however, attempting to run RSS with these values eventually failed with

```
Bad configuration for setting up rack: unable to parse rack_network_config.uplink_up as IpAddr: invalid IP address syntax
```

If we're trying to parse values as `IpAddr`, I think we should be able to make the fields `IpAddr` from the top.
