### ISSUE TITLE
api spec issues

### ISSUE THREAD

**Issue by jessfraz** [oxidecomputer/omicron#535]
1. The spec fails to validate, might want to run a validation on commits that change it, here's a sample github action, take it or leave it:
```
name: validate-openapi-spec
on:
  pull_request:
    paths:
      - .github/workflows/validate-openapi-spec.yml
      - spec.json
  workflow_dispatch:
    inputs:
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install our tools
        shell: bash
        run: |
          npm install -g @apidevtools/swagger-cli
      - name: Run validation
        shell: bash
        run: |
          swagger-cli validate spec.json
```

Replace with the path to the spec....

2. Nothing has tags, if we want to generate docs or anything else, tags would be _very_ VERY useful... right now, this makes generating anything super annoying...
